import { Router, type IRouter } from "express";
import healthRouter from "./health";
import dashboardRouter from "./dashboard";
import packagesRouter from "./packages";
import regulationsRouter from "./regulations";
import suppliersRouter from "./suppliers";
import supplierSubmissionsRouter from "./supplier-submissions";
import miscRouter from "./misc";
import aiProvidersRouter from "./ai-providers";
import violationsRouter from "./violations";
import languageRouter from "./language";
import claimsRouter from "./claims";
import ocrRouter from "./ocr";
import documentAiRouter from "./document-ai";
import storageRouter from "./storage";
import fdaRouter from "./fda";
import ecfrRouter from "./ecfr";
import meRouter from "./me";
import reviewsRouter from "./reviews";
import usersRouter from "./users";
import teamsRouter from "./teams";
import opsRouter from "./ops";
import complianceMemoryRouter from "./compliance-memory";
import proofingRouter from "./proofing";
import policiesRouter from "./policies";
import sopDocumentsRouter from "./sop-documents";
import glossaryRouter from "./glossary";
import resourcesRouter from "./resources";
import usageRouter from "./usage";
import trainingRouter from "./training";
import specialistsRouter from "./specialists";
import departmentsRouter from "./departments";
import routingRulesRouter from "./routing-rules";
import reviewStagesRouter from "./review-stages";
import escalationRulesRouter from "./escalation-rules";
import workloadRouter from "./workload";
import assistantRouter from "./assistant";
import workspaceRouter from "./workspace";
import { requireAuth } from "../middlewares/requireAuth";

const router: IRouter = Router();

// Health check stays public; everything below requires a signed-in Dollar Tree user.
router.use(healthRouter);
router.use(requireAuth);
router.use(meRouter);
router.use(dashboardRouter);
router.use(packagesRouter);
router.use(regulationsRouter);
router.use(suppliersRouter);
router.use(supplierSubmissionsRouter);
router.use(miscRouter);
router.use(aiProvidersRouter);
router.use(violationsRouter);
router.use(languageRouter);
router.use(claimsRouter);
router.use(ocrRouter);
router.use(documentAiRouter);
router.use(proofingRouter);
router.use(storageRouter);
router.use(fdaRouter);
router.use(ecfrRouter);
router.use(reviewsRouter);
router.use(usersRouter);
router.use(teamsRouter);
router.use(opsRouter);
router.use(complianceMemoryRouter);
router.use(policiesRouter);
router.use(sopDocumentsRouter);
router.use(glossaryRouter);
router.use(resourcesRouter);
router.use(usageRouter);
router.use(trainingRouter);
router.use(specialistsRouter);
router.use(departmentsRouter);
router.use(routingRulesRouter);
router.use(reviewStagesRouter);
router.use(escalationRulesRouter);
router.use(workloadRouter);
router.use(assistantRouter);
router.use(workspaceRouter);

export default router;
